displayName=Imbued heartache
author=joachlar
description=Gives you your imbued heart rate and superior kc by typing "!Heart", or "!Heart elite" if you've done elite ca's.
tags=slayer, imbued heart, heart, superior creature, superior
plugins=imbuedHeartache.ImbuedHeartachePlugin
build=standard
